import os
import json
import asyncio
from typing import AsyncGenerator, Dict, Any, List
from contextlib import AsyncExitStack

from langchain_openai import ChatOpenAI
from langchain_core.messages import BaseMessage, HumanMessage, ToolMessage
from langgraph.checkpoint.memory import MemorySaver
from deepagents import create_deep_agent

# Import our tools
from sandbox_e2b import TOOLS

# System Prompt
SYSTEM_PROMPT = """你是一个运行在 E2B 沙箱中的顶级 Python 编程智能体。

**核心原则:**
1.  **代码优先**: 优先编写并运行 Python 代码解决问题。
2.  **效率至上 (合并操作)**:
    *   **拒绝碎片化**: 严禁为了 `mkdir`、`ls` 或 `pip install` 这种简单操作单独发起一轮对话。
    *   **批处理**: 必须在一个 `run_code` 块中完成一系列相关任务（如：同时创建目录、写入多个文件、安装依赖、执行逻辑）。
    *   **Shell 技巧**: 如果必须用 Shell，请使用 `&&` 连接多条命令 (e.g., `mkdir -p data && cd data && touch test.txt`)。
3.  **文件操作**: 读写文件务必使用 UTF-8 编码。
4.  **可视化与展示 (强制要求)**:
    *   **首选 Plotly** 生成交互式图表。
    *   **HTML 模板**: 生成任何 HTML 报告/应用时，必须使用下方提供的专业骨架。
    *   **展示铁律**: 任务结束前，必须检查是否生成了文件（如 .html, .png, .svg）。如果是，**必须调用 `visualize_file(path)` 进行预览展示**。这是衡量任务成功的唯一标准。

**HTML 报告骨架 (Swiss Modernism 2.0):**
```html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manus Analysis Report</title>
    <script src="https://cdn.tailwindcss.com?plugins=typography"></script>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600&family=Poppins:wght@600;700&display=swap" rel="stylesheet">
    <style>
        body { font-family: 'Open Sans', sans-serif; background-color: #F8FAFC; color: #1E293B; }
        h1, h2, h3, h4 { font-family: 'Poppins', sans-serif; letter-spacing: -0.025em; color: #0F172A; }
        .prose { max-width: none; }
        .report-card { background: white; border-radius: 1rem; padding: 2rem; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05), 0 2px 4px -1px rgba(0,0,0,0.03); border: 1px solid #E2E8F0; margin-bottom: 2rem; }
    </style>
</head>
<body class="bg-slate-50 min-h-screen py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-5xl mx-auto bg-white shadow-xl rounded-2xl border border-slate-100 overflow-hidden">
        <div class="bg-slate-900 px-8 py-10 text-white">
            <div class="flex items-center gap-3 mb-4">
                <span class="px-2 py-1 rounded bg-blue-500/20 border border-blue-400/30 text-blue-300 text-xs font-bold tracking-wider uppercase">Manus Report</span>
            </div>
            <h1 class="text-4xl font-bold text-white mb-2 tracking-tight">数据分析报告</h1>
            <p class="text-slate-400 text-lg font-light">由 AI 智能体自动生成</p>
        </div>
        <div class="p-8 md:p-12">
            <article class="prose prose-slate prose-lg">
                {content}
            </article>
        </div>
        <div class="bg-slate-50 border-t border-slate-100 px-8 py-6 text-center">
            <p class="text-sm text-slate-400">Generated by MyManus &bull; Powered by E2B & LangGraph</p>
        </div>
    </div>
</body>
</html>
```

请始终使用中文与用户交流。
"""

class ManusAgent:
    def __init__(self):
        api_key = os.getenv("DEEPSEEK_API_KEY")
        base_url = os.getenv("DEEPSEEK_BASE_URL")
        self.model_id = os.getenv("MODEL_ID", "deepseek-ai/DeepSeek-V3")
        
        if not api_key:
            print("[Warning] DEEPSEEK_API_KEY not found.")
            self.model = None
        else:
            self.model = ChatOpenAI(
                api_key=api_key, 
                base_url=base_url,
                model=self.model_id,
                streaming=True
            )
            
        self.tools = TOOLS
        
        # Use create_deep_agent from deepagents library
        if self.model:
            self.graph = create_deep_agent(
                model=self.model,
                tools=self.tools,
                system_prompt=SYSTEM_PROMPT,
                checkpointer=MemorySaver()
            )
        else:
            self.graph = None

    async def run(self, task: str) -> AsyncGenerator[Dict[str, Any], None]:
        """
        Executes the agent loop using deepagents.create_deep_agent.
        """
        if not self.graph:
            yield {"type": "error", "message": "Agent not initialized (check API Key)."}
            return

        yield {"type": "system", "message": "Manus Agent initialized (DeepAgents Mode)."}

        # Initialize Sandbox for this session
        yield {"type": "status", "message": "Initializing E2B Sandbox..."}
        from e2b_code_interpreter import AsyncSandbox
        
        try:
            async with AsyncExitStack() as stack:
                sb = await AsyncSandbox.create("code-interpreter-v1")
                sandbox = await stack.enter_async_context(sb)
                yield {"type": "system", "message": f"Sandbox created: {sandbox.sandbox_id}"}
                
                # Config with sandbox
                config = {
                    "configurable": {
                        "thread_id": "session_1",
                        "sandbox": sandbox
                    },
                    "recursion_limit": 100
                }

                # Input format for deepagents usually expects a list of messages
                inputs = {"messages": [HumanMessage(content=task)]}

                current_turn = 0
                
                # Use astream_events to pipe results to frontend
                async for event in self.graph.astream_events(inputs, config=config, version="v2"):
                    kind = event["event"]
                    
                    if kind == "on_chat_model_start":
                        current_turn += 1
                        yield {"type": "status", "message": f"Thinking (Turn {current_turn})..."}

                    elif kind == "on_chat_model_stream":
                        content = event["data"]["chunk"].content
                        if content:
                            yield {"type": "thought", "content": content}

                    elif kind == "on_chat_model_end":
                        output = event["data"].get("output")
                        if output:
                            tool_calls = getattr(output, "tool_calls", [])
                            if tool_calls:
                                yield {
                                    "type": "step_summary",
                                    "thought": output.content,
                                    "tool_calls": [
                                        {"name": tc["name"], "args": tc["args"]} 
                                        for tc in tool_calls
                                    ]
                                }
                            elif output.content:
                                yield {
                                    "type": "answer",
                                    "content": output.content
                                }
                            
                    elif kind == "on_tool_start":
                        yield {"type": "status", "message": f"Calling tool: {event['name']}"}
                        
                    elif kind == "on_tool_end":
                        output = event["data"].get("output")
                        
                        # Try to extract content string
                        content_str = ""
                        if isinstance(output, ToolMessage):
                            content_str = output.content
                        else:
                            content_str = str(output)

                        # Try to detect if it's a visualization payload
                        is_preview = False
                        try:
                            # Heuristic: only try parsing if it looks like JSON object
                            if content_str.strip().startswith("{"):
                                data = json.loads(content_str)
                                if data.get("type") == "file_preview":
                                    yield {
                                        "type": "preview", 
                                        "mime": data["mime"], 
                                        "content": data["content"], 
                                        "path": data["path"]
                                    }
                                    yield {"type": "output", "content": f"(File '{data['path']}' sent to preview)"}
                                    is_preview = True
                        except:
                            pass
                        
                        # If not a preview, just output the content
                        if not is_preview:
                            yield {"type": "output", "content": content_str}

                yield {"type": "success", "message": "Task completed."}

        except Exception as e:
            yield {"type": "error", "message": f"Agent Error: {str(e)}"}
            import traceback
            traceback.print_exc()

if __name__ == "__main__":
    agent = ManusAgent()
    async def main():
        async for msg in agent.run("Print hello"):
            print(msg)
    asyncio.run(main())
